In [8]:
import pandas as pd
import seaborn as sns
 
# Load the Seaborn's taxis dataset
taxis_df = sns.load_dataset('taxis')
 
print(taxis_df.info())

# Set 'pickup' column as the datetime index
taxis_df.set_index('pickup', inplace=True)
 
# print the newly set index
print(taxis_df.index[:5])

taxis_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB
None
DatetimeIndex(['2019-03-23 20:21:09', '2019-03-04 16:11:55',
               '2019-03-27 17:53:01', '2019-03-10 01:23:59',
               '2019-03-30 13:27:42'],
              dtype='datetime64[ns]', name='pickup', freq=None)

,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
pickup,,,,,,,,,,,,,
2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [5]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Requirement already satisfied: pandas>=1.2 in c:\users\a040699\appdata\roaming\python\python310\site-packages (from seaborn) (2.3.3)
Collecting matplotlib!=3.6.1,>=3.4
  Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl (8.2 MB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\a040699\appdata\roaming\python\python310\site-packages (from seaborn) (2.2.6)
Collecting pyparsing>=3
  Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting pillow>=8
  Downloading pillow-12.3.0-cp310-cp310-win_amd64.whl (7.2 MB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\a040699\appdata\roaming\python\python310\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.5.0-cp310-cp310-win_amd64.whl (73 kB)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\a040699\appdata\roaming\python\python310\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.63.0-cp310-cp310-win_amd64.whl (1.6 MB)
Requirement already satisfied: tzdata>=2022.7 in c:\users\a040699\appdata\roaming\python\python310\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\a040699\appdata\roaming\python\python310\site-packages (from pandas>=1.2->seaborn) (2026.3.post1)
Requirement already satisfied: six>=1.5 in c:\users\a040699\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.10.9 pillow-12.3.0 pyparsing-3.3.2 seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Program Files\Python\python.exe -m pip install --upgrade pip' command.

In [9]:
# Sample weather dataset with date-time columns
data = {'Date': ['2023-08-01', '2023-08-02', '2023-08-03'],
        'Temperature_C': [25.5, 26.2, 24.8],
        'Humidity': [65, 70, 60]}
 
weather_df = pd.DataFrame(data)
 
# print the dtype of 'Date' column
print(weather_df['Date'].dtypes) # Output: object
 
# Convert 'Date' column to datetime
weather_df['Date'] = pd.to_datetime(weather_df['Date']) 

# print the dtype of 'Date' column
print(weather_df['Date'].dtypes) # Output: datetime64[ns]
weather_df

object
datetime64[ns]

        Date  Temperature_C  Humidity
0 2023-08-01           25.5        65
1 2023-08-02           26.2        70
2 2023-08-03           24.8        60

In [14]:
import pandas as pd
import seaborn as sns
 
# Load the Seaborn's taxis dataset
taxis = sns.load_dataset('taxis')
 
print(taxis_df.info())

# Set "pickup" as the index
taxis.set_index("pickup", inplace=True)
 
# Sort the DataFrame by the index (pickup dates) in ascending order
taxis.sort_index(inplace=True)
 
# Display the modified DataFrame for selected column
print(taxis[['dropoff', 'fare']].head())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6433 entries, 2019-03-23 20:21:09 to 2019-03-13 19:31:22
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   dropoff          6433 non-null   datetime64[ns]
 1   passengers       6433 non-null   int64
 2   distance         6433 non-null   float64
 3   fare             6433 non-null   float64
 4   tip              6433 non-null   float64
 5   tolls            6433 non-null   float64
 6   total            6433 non-null   float64
 7   color            6433 non-null   object
 8   payment          6389 non-null   object
 9   pickup_zone      6407 non-null   object
 10  dropoff_zone     6388 non-null   object
 11  pickup_borough   6407 non-null   object
 12  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(6)
memory usage: 703.6+ KB
None
                                dropoff  fare
pickup
2019-02-28 23:29:03 2019-02-28 23:32:35   5.0
2019-03-01 00:03:29 2019-03-01 00:13:32  10.0
2019-03-01 00:08:32 2019-03-01 00:29:47  22.5
2019-03-01 00:15:53 2019-03-01 00:47:58  25.5
2019-03-01 00:29:22 2019-03-01 00:32:48   4.5