In [4]:
import pandas as pd
df = pd.DataFrame(
    {"101":["Sales","Mumbai"],
                   "102":["SW","Pune"],
                   "103":["Architects","Chenna"]
                   })

df.describe()
df.columns
df.first
df.last
df.head(2)
df.tail(2)

      101   102         103
0   Sales    SW  Architects
1  Mumbai  Pune      Chenna

In [ ]:
#understand structure of data provided by source(first setp before data cleaning or going further)
import pandas as pd

empdf=pd.read_csv("employees.csv")
print(empdf.describe())
empdf.head(10)#value retrival
print("Shape(Rows:Columns)",empdf.shape)
print("Types:",empdf.dtypes)
print("Information(Rows:Columns)",empdf.info())
print("Columns:",empdf.columns)

#object means the row/column has mixed set of values

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000
Shape(Rows:Columns) (1000, 8)
Types: First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB
Information(Rows:Columns) None
Columns: Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [12]:
empdf.tail(5)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [15]:
print("Shape(Rows:Columns)",empdf.shape)

Shape(Rows:Columns) (1000, 8)

In [24]:
#understand structure o fdata provided by source
empdf = pd.read_csv("employees.csv")
empdf.tail(10)#value retrival
print(empdf.items)

<bound method DataFrame.items of     First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]>

In [25]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])

# Access the rows of the DataFrame
result = df.index
print('Output Accessed Row Labels:', result)

Output Accessed Row Labels: Index(['r1', 'r2', 'r3', 'r4'], dtype='object')

In [26]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])

# Display the Input DataFrame
print('Input DataFrame:\n', df)

# Modify the Row labels of the DataFrame
df.index = [100, 200, 300, 400]
print('Output Modified DataFrame with the updated index labels:\n', df)

Input DataFrame:
      Name  Age  Gender  Rating
r1  Steve   32    Male    3.45
r2    Lia   28  Female    4.60
r3    Vin   45    Male    3.90
r4  Katie   38  Female    2.78
Output Modified DataFrame with the updated index labels:
       Name  Age  Gender  Rating
100  Steve   32    Male    3.45
200    Lia   28  Female    4.60
300    Vin   45    Male    3.90
400  Katie   38  Female    2.78

In [27]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])

# Access the column labels of the DataFrame
result = df.columns
print('Output Accessed column Labels:', result)

Output Accessed column Labels: Index(['Name', 'Age', 'Gender', 'Rating'], dtype='object')

In [28]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])
    
# Display the Input DataFrame
print('Input DataFrame:\n', df)

# Modify the Column labels of the DataFrame
df.columns = ['Col1', 'Col2', 'Col3', 'Col4']
print('Output Modified DataFrame with the updated Column Labels\n:', df)

Input DataFrame:
      Name  Age  Gender  Rating
r1  Steve   32    Male    3.45
r2    Lia   28  Female    4.60
r3    Vin   45    Male    3.90
r4  Katie   38  Female    2.78
Output Modified DataFrame with the updated Column Labels
:      Col1  Col2    Col3  Col4
r1  Steve    32    Male  3.45
r2    Lia    28  Female  4.60
r3    Vin    45    Male  3.90
r4  Katie    38  Female  2.78

In [ ]:
#https://www.tutorialspoint.com/python_pandas/python_pandas_accessing_dataframe.htm

In [ ]:
import pandas as pd

empdf=pd.read_csv("employees.csv")

#slicing methods for rows
# empdf.iloc[4:12]
# result=empdf.loc[10:15,"First Name"]
# print(result)

#slicing for coloumns with rows

resultcol = empdf.iloc[10:15,3:5] #always in format rows : columns
print(resultcol)

   Last Login Time  Salary
10         9:01 AM   63241
11         3:19 PM  102508
12         1:08 AM  112807
13        11:40 PM  109831
14         7:13 AM   41426

In [37]:

empdf=pd.read_csv("employees.csv")

# Slice a single column
col_A = empdf.loc[:, "First Name"]
print("Slicing a single column A using iloc[]:")
print(col_A)

# Slice multiple columns

cols_AB = empdf.loc[:, "First Name":"Gender"]
print("Slicing multiple columns A and B using iloc[]:")
print(cols_AB)

# sal = empdf.loc[:,"Salary"]
# sum(sal)
# 

bonus = empdf.loc[:,"Bonus %"]
sum(bonus)

Slicing a single column A using iloc[]:
0      Douglas
1       Thomas
2        Maria
3        Jerry
4        Larry
        ...
995      Henry
996    Phillip
997    Russell
998      Larry
999     Albert
Name: First Name, Length: 1000, dtype: object
Slicing multiple columns A and B using iloc[]:
    First Name  Gender
0      Douglas    Male
1       Thomas    Male
2        Maria  Female
3        Jerry    Male
4        Larry    Male
..         ...     ...
995      Henry     NaN
996    Phillip    Male
997    Russell    Male
998      Larry    Male
999     Albert    Male

[1000 rows x 2 columns]

10207.554999999998

In [15]:
import pandas as pd

custdf = pd.read_json("myfile.json")
custdf.describe()

compdf = pd.read_xml("employees.xml", parser="etree")
compdf.head(8)

   empid empname location
0    101  Ganesh     Pune
1    102  Mahesh     Pune

In [22]:
mydf=pd.read_html("myfile.html")
mydf[0].describe()

            EmpID
count    2.000000
mean   101.500000
std      0.707107
min    101.000000
25%    101.250000
50%    101.500000
75%    101.750000
max    102.000000

In [17]:
pip install lxml

Note: you may need to restart the kernel to use updated packages.Defaulting to user installation because normal site-packages is not writeable
Collecting lxml
  Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl (4.0 MB)
Installing collected packages: lxml
Successfully installed lxml-6.1.1

WARNING: You are using pip version 21.2.4; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Program Files\Python\python.exe -m pip install --upgrade pip' command.

In [27]:
import pandas as pd

productsdf = pd.read_json("Products.json")
productsdf.describe()
productsdf["value"]

0     {'ID': 0, 'Name': 'Bread', 'Description': 'Who...
1     {'ID': 1, 'Name': 'Milk', 'Description': 'Low ...
2     {'ID': 2, 'Name': 'Vint soda', 'Description': ...
3     {'ID': 3, 'Name': 'Havina Cola', 'Description'...
4     {'ID': 4, 'Name': 'Fruit Punch', 'Description'...
5     {'ID': 5, 'Name': 'Cranberry Juice', 'Descript...
6     {'ID': 6, 'Name': 'Pink Lemonade', 'Descriptio...
7     {'ID': 7, 'Name': 'DVD Player', 'Description':...
8     {'ID': 8, 'Name': 'LCD HDTV', 'Description': '...
9     {'@odata.type': '#ODataDemo.FeaturedProduct', ...
10    {'@odata.type': '#ODataDemo.FeaturedProduct', ...
Name: value, dtype: object

In [31]:
orcdf=pd.read_orc("orcfile.orc")
orcdf.describe()

ArrowException: Unknown error: Time zone file /usr/share/zoneinfo/UTC does not exist. Please install IANA time zone database and set TZDIR env.

In [ ]:
pip install pyarrow.orc

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pyarrow.orc (from versions: none)
ERROR: No matching distribution found for pyarrow.orc
WARNING: You are using pip version 21.2.4; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Program Files\Python\python.exe -m pip install --upgrade pip' command.

WARNING: You are using pip version 21.2.4; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Program Files\Python\python.exe -m pip install --upgrade pip' command.

Defaulting to user installation because normal site-packages is not writeable
Collecting pyarrow
  Downloading pyarrow-25.0.1-cp310-cp310-win_amd64.whl (27.8 MB)
Installing collected packages: pyarrow
Successfully installed pyarrow-25.0.1

In [32]:
orcdf=pd.read_orc("orc_metadata_sample.orc")
orcdf.describe()

       byte1  short1  int1         long1  float1  double1
count    1.0     1.0   1.0  1.000000e+00  1.0000    1.000
mean   127.0  1024.0  42.0  4.509716e+10  3.1415   -2.713
std      NaN     NaN   NaN           NaN     NaN      NaN
min    127.0  1024.0  42.0  4.509716e+10  3.1415   -2.713
25%    127.0  1024.0  42.0  4.509716e+10  3.1415   -2.713
50%    127.0  1024.0  42.0  4.509716e+10  3.1415   -2.713
75%    127.0  1024.0  42.0  4.509716e+10  3.1415   -2.713
max    127.0  1024.0  42.0  4.509716e+10  3.1415   -2.713

In [2]:
import pandas as pd
paradf=pd.read_parquet("sample-users.parquet")
paradf.describe()

           user_id          age      balance                 signup_date
count  1000.000000  1000.000000  1000.000000                        1000
mean    500.500000    46.672000  5082.639590  2022-10-23 10:45:07.200000
min       1.000000    18.000000    34.730000         2020-01-01 00:00:00
25%     250.750000    32.000000  2742.807500         2021-06-03 06:00:00
50%     500.500000    47.000000  5097.490000         2022-12-07 00:00:00
75%     750.250000    61.000000  7534.075000         2024-02-14 12:00:00
max    1000.000000    75.000000  9995.950000         2025-06-22 00:00:00
std     288.819436    16.946374  2859.475186                         NaN

In [3]:
import pandas as pd
paradf=pd.read_parquet("search_trends.parquet")
paradf.describe()

,Matthew Perry,chandrayaan-3,titanic submarine,hurricane lee,maine shooting,nashville shooting,Tina Turner,Ken Block,Lil Tay,Jerry Springer,Angus Cloud,Nicola Bulley,Jason Aldean,Joe Jonas,Smash Mouth
count,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000
mean,2.326531,2.571429,1.653061,0.877551,0.632653,0.836735,1.959184,0.714286,1.061224,1.122449,1.551020,1.102041,0.979592,0.551020,0.265306
std,14.287797,14.250731,10.441406,4.161493,4.146755,5.428885,7.947639,4.573474,5.753290,6.290312,9.851102,3.519262,3.332228,2.082279,1.717259
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,100.000000,100.000000,73.000000,24.000000,29.000000,38.000000,56.000000,32.000000,40.000000,44.000000,69.000000,17.000000,19.000000,14.000000,12.000000

In [4]:
orc1df=pd.read_orc("orc_test1_sample.orc")
orc1df.describe()

            byte1       short1     int1         long1    float1    double1
count    2.000000     2.000000      2.0  2.000000e+00  2.000000   2.000000
mean    50.500000  1536.000000  65536.0  9.223372e+18  1.500000 -10.000000
std     70.003571   724.077344      0.0  0.000000e+00  0.707107   7.071068
min      1.000000  1024.000000  65536.0  9.223372e+18  1.000000 -15.000000
25%     25.750000  1280.000000  65536.0  9.223372e+18  1.250000 -12.500000
50%     50.500000  1536.000000  65536.0  9.223372e+18  1.500000 -10.000000
75%     75.250000  1792.000000  65536.0  9.223372e+18  1.750000  -7.500000
max    100.000000  2048.000000  65536.0  9.223372e+18  2.000000  -5.000000

In [ ]:
import pandas as pd
xl1df=pd.read_excel("employees.xlsx")
xl1df.describe()

sorted_df=xl1df.sort_values("Salary")#returns data frame object
sorted_df.head()

newseries=xl1df["Salary"].sort_values()
newseries.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
576,Michael,Male,1993-07-30,17:35:00,35013,14.879,0.0,Product
238,Kevin,Male,1982-03-25,07:31:00,35061,5.128,0.0,Legal
82,Steven,Male,1980-03-30,21:20:00,35095,8.379,1.0,Client Services
63,Matthew,Male,2013-01-02,22:33:00,35203,18.040,0.0,Human Resources
650,Cynthia,Female,1986-07-05,01:24:00,35381,11.749,0.0,Finance

In [11]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

WARNING: You are using pip version 21.2.4; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Program Files\Python\python.exe -m pip install --upgrade pip' command.

In [2]:
import pandas as pd
xl1df=pd.read_excel("employees.xlsx")
xl1df.describe()

newseries=xl1df["Salary"].sort_values()
newseries.head()

576    35013
238    35061
82     35095
63     35203
650    35381
Name: Salary, dtype: int64

In [3]:
import pandas as pd
xl1df=pd.read_excel("employees.xlsx")
xl1df.describe()

sumsal=xl1df["Salary"].sum()
print(sumsal)

90662181

In [9]:
import pandas as pd
xl1df=pd.read_excel("employees.xlsx")
xl1df.describe()

print("Count of rows with no gender values:",xl1df["Gender"].isna().sum())
xl1df["Gender"].fillna("No Gender",inplace=True)
print("Count of rows with no gender values:",xl1df["Gender"].isna().sum())

Count of rows with no gender values: 145
Count of rows with no gender values: 0

C:\Users\A040699\AppData\Local\Temp\ipykernel_30760\3410555206.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  xl1df["Gender"].fillna("No Gender",inplace=True)

In [ ]:
import numpy as np

xl1df=pd.read_excel("employees.xlsx")
print("count of rows with no SM values:",xl1df["Senior Management"].isna().sum())
emp=xl1df["Senior Management"].replace(to_replace=np.nan,value=True)# since to_replace returns a series so we stored it in emp(a new object),which will then give us the count on that row and returns

print("count of rows with no SM values:",emp.isna().sum())

count of rows with no SM values: 67
count of rows with no SM values: 0

In [ ]:
productsdf=pd.read_csv("products-1000.csv")
productsdf.describe()
productsdf.shape
print(productsdf.columns)
# productsdf.groupby("Category").count()
# productsdf.groupby("Colour").count()
productsdf.groupby("Availability").count()
print(productsdf.groupby("Size").count())

#now we start analysis 
eankurtosis=productsdf["EAN"].kurtosis()
print("Kurtosis on EAN",eankurtosis)


productsdf["Category"].skew
print(round(productsdf["Stock"].kurtosis(),3))
print(round(productsdf["Price"].skew(),3))
print("Mean Value of Price",round(productsdf["Price"].mean(),3))
print("Median Value of Price",round(productsdf["Price"].median(),3))
print("Min:",min(productsdf["Price"]))
print("Max :",max(productsdf["Price"]))

#aggregating values

# dfagg=productsdf.groupby("Availability").agg({"Price":"mean","Stock":"sum"}) #business pov-the loss we are incuring due to stock-out of products
# print(dfagg)

# dfagg=productsdf.groupby("Color").agg({"Price":"mean","Stock":"sum"})
# print(dfagg)

dfagg=productsdf.groupby("Category").aggregate({"Price":"median","Stock":"sum"}) #
print(dfagg)

Index(['Index', 'Name', 'Description', 'Brand', 'Category', 'Price',
       'Currency', 'Stock', 'EAN', 'Color', 'Size', 'Availability',
       'Internal ID'],
      dtype='object')
             Index  Name  Description  Brand  Category  Price  Currency  \
Size
100x200 mm      59    59           59     59        59     59        59
10x10 cm        64    64           64     64        64     64        64
12x18 in        47    47           47     47        47     47        47
15x20 cm        54    54           54     54        54     54        54
30x40 cm        46    46           46     46        46     46        46
50x70 cm        56    56           56     56        56     56        56
5x7 in          52    52           52     52        52     52        52
8x10 in         73    73           73     73        73     73        73
Extra Large     49    49           49     49        49     49        49
L               65    65           65     65        65     65        65
Large           58    58           58     58        58     58        58
M               55    55           55     55        55     55        55
Medium          48    48           48     48        48     48        48
S               60    60           60     60        60     60        60
Small           52    52           52     52        52     52        52
XL              58    58           58     58        58     58        58
XS              50    50           50     50        50     50        50
XXL             54    54           54     54        54     54        54

             Stock  EAN  Color  Availability  Internal ID
Size
100x200 mm      59   59     59            59           59
10x10 cm        64   64     64            64           64
12x18 in        47   47     47            47           47
15x20 cm        54   54     54            54           54
30x40 cm        46   46     46            46           46
50x70 cm        56   56     56            56           56
5x7 in          52   52     52            52           52
8x10 in         73   73     73            73           73
Extra Large     49   49     49            49           49
L               65   65     65            65           65
Large           58   58     58            58           58
M               55   55     55            55           55
Medium          48   48     48            48           48
S               60   60     60            60           60
Small           52   52     52            52           52
XL              58   58     58            58           58
XS              50   50     50            50           50
XXL             54   54     54            54           54
Kurtosis on EAN -1.1974659340471765
-1.215
0.036
Mean Value of Price 506.549
Median Value of Price 497.5
Min: 1
Max : 999
                                 Price  Stock
Category
Accessories (Bags, Hats, Belts)  533.0  12007
Automotive                       392.0  15689
Beauty & Personal Care           615.0  15634
Bedding & Bath                   420.0   7982
Books & Stationery               460.0  19858
Cameras & Accessories            542.5  13307
Camping & Hiking                 362.0  18195
Cleaning Supplies                413.0  17340
Clothing & Apparel               520.0  17945
Cycling                          413.0  16463
Fishing & Hunting                478.0  15067
Fitness Equipment                606.0   6873
Fragrances                       451.0  15759
Furniture                        533.5  14824
Grooming Tools                   553.5  16272
Haircare                         500.0  14489
Headphones & Earbuds             432.0  15973
Health & Wellness                568.0  17780
Home & Kitchen                   580.0  19524
Home Decor                       518.0  17454
Kids' Clothing                   647.5  11086
Kitchen Appliances               428.0  16326
Laptops & Computers              385.0  13147
Makeup                           532.0  12583
Men's Clothing                   344.5   9216
Office Supplies                  398.0  12264
Shoes & Footwear                 622.0  15388
Skincare                         490.5  17205
Smartphones                      524.5  13355
Smartwatches                     461.5  20164
Sports & Outdoors                468.0  13874
Team Sports                      544.0  14317
Toys & Games                     447.5  11476
Women's Clothing                 508.0  12946

In [ ]:
# Data manipulation

In [53]:
import pandas as pd

# define a dictionary containing student data
data = {'Name': ['John', 'Emma', 'Michael', 'Sophia'],
        'Height': [5.5, 6.0, 5.8, 5.3],
        'Qualification': ['BSc', 'BBA', 'MBA', 'BSc']}

# convert the dictionary into a DataFrame
df = pd.DataFrame(data)

print("Original dataframe:")
print (df)
print ()


#adding a coloumn of address to a data frame

# declare a new list
# address = ['New York', 'London', 'Sydney', 'Toronto'] #

# # assign the list as a column
# df['Address'] = address

#Adding Row to a Data Frame
# add a new row
df.loc[len(df.index)] = ['Amy', 5.2, 'BIT'] 
print("Modified DataFrame:")
df

Original dataframe:
      Name  Height Qualification
0     John     5.5           BSc
1     Emma     6.0           BBA
2  Michael     5.8           MBA
3   Sophia     5.3           BSc

Modified DataFrame:

      Name  Height Qualification
0     John     5.5           BSc
1     Emma     6.0           BBA
2  Michael     5.8           MBA
3   Sophia     5.3           BSc
4      Amy     5.2           BIT

In [45]:
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Felipe', 'Rita'],
        'Age': [25, 30, 35, 40, 22, 29],
        'City': ['New York', 'London', 'Paris', 'Tokyo', 'Bogota', 'Banglore']}
df = pd.DataFrame(data)

# display the original DataFrame
print("Original DataFrame:")
print(df)
print()

#assigning list as coloumn

#drop/delete row
df.drop(index=1)


# # delete row with index 4
# df.drop("Age", axis=1, inplace=True) #axis is for removing column

# # delete row with index 5
# df.drop(index=5, inplace=True)

# # delete rows with index 1 and 3
# df.drop([1, 3], axis=0, inplace=True)

# display the modified DataFrame after deleting rows
print("Modified DataFrame:")
print(df)

Original DataFrame:
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo
4   Felipe   22    Bogota
5     Rita   29  Banglore

Modified DataFrame:
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo
4   Felipe   22    Bogota
5     Rita   29  Banglore

In [48]:
#drop rows with null values

import pandas as pd
 
import numpy as np
 
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
df = pd.DataFrame(dict)
df.dropna(inplace=True)
 
df

   First Score  Second Score  Third Score
1         90.0          45.0         40.0

In [50]:
import pandas as pd
  
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 

df = pd.DataFrame(dict)

for i,j in df.iterrows():
    print(i,j)
    print(df)

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object
     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98
1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object
     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98
2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object
     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98
3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object
     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98